"""Alterando timestamp das mensagens de 'Date' para 'DateTime'

Revision ID: 006e279fcf04
Revises: 76a8273c64e3
Create Date: 2025-03-04 00:46:52.553784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006e279fcf04'
down_revision = '76a8273c64e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
