"""Adicionando 'description' e 'instructions' no Space

Revision ID: 43671243da50
Revises: 006e279fcf04
Create Date: 2025-03-09 02:06:46.484281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43671243da50'
down_revision = '006e279fcf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_column('instructions')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
