"""Adicionando campo 'name' às Threads

Revision ID: 76a8273c64e3
Revises: 77be52d40612
Create Date: 2025-02-23 19:38:49.854943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a8273c64e3'
down_revision = '77be52d40612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
